#!/bin/bash
set -e

if [ ! -d "/home/vagrant/pgtap/" ]; then
	git clone https://github.com/theory/pgtap.git
fi

pushd pgtap
make && sudo make install && make installcheck
popd

sudo PERL_MM_USE_DEFAULT=1 cpan TAP::Parser::SourceHandler::pgTAP

psql -c 'CREATE EXTENSION pgtap;'
