#!/bin/bash
set -e

if [ ! -d "/home/vagrant/pgtap/" ]; then
	git clone https://github.com/theory/pgtap.git

	pushd pgtap
	make && sudo make install && make installcheck
	popd
fi

psql -d minerva -c 'CREATE EXTENSION pgtap;'
