#!/bin/bash

DEFAULT_INSTANCE=${DEFAULT_MINERVA_INSTANCE:-default}

INSTANCE=${1:-$DEFAULT_INSTANCE}
instance_conf_file="/etc/minerva/instances/$INSTANCE.conf"

function get_conf_value()
{
    local filepath=$1
    local name=$2

    grep -e "^$name\s*=.*" $filepath | sed -re "s/^$name\s*=\s*(.*)/\1/g"
}

host=$(get_conf_value "$instance_conf_file" "host")
port=$(get_conf_value "$instance_conf_file" "port")
db=$(get_conf_value "$instance_conf_file" "name")

psql -h $host -p $port $db minerva_admin -c '
BEGIN;
TRUNCATE TABLE directory.entitytaglink_tagarray;
INSERT INTO directory.entitytaglink_tagarray
    SELECT entity_id, array_agg(tag_id)
    FROM directory.entitytaglink
    GROUP BY entity_id;
COMMIT;
'
