#!/bin/bash

DEFAULT_INSTANCE=${DEFAULT_MINERVA_INSTANCE:-default}

INSTANCE=${1:-$DEFAULT_INSTANCE}
instance_conf_file="/etc/minerva/instances/$INSTANCE.conf"

function get_conf_value()
{
    local filepath=$1
    local name=$2

    grep -e "^$name\s*=.*" $filepath | sed -re "s/^$name\s*=\s*(.*)/\1/g"
}

host=$(get_conf_value "$instance_conf_file" host)
port=$(get_conf_value "$instance_conf_file" port)
db=$(get_conf_value "$instance_conf_file" name)

psql -h $host -p $port $db minerva_admin -c '
BEGIN;
TRUNCATE TABLE directory.entitytaglink_tagarray;
INSERT INTO directory.entity_link_denorm
SELECT entity.id, (
    SELECT array_agg(lower(tag.name))
    FROM directory.entitytaglink
    INNER JOIN directory.tag ON tag_id = tag.id
    WHERE entity_id = entity.id
), entity.name
FROM directory.entity;
COMMIT;
ANALYZE directory.entity_link_denorm;
'
