#!/bin/bash

DEFAULT_INSTANCE=${MINERVA_INSTANCE:-default}

INSTANCE=${1:-$DEFAULT_INSTANCE}
instance_conf_file="/etc/minerva/instances/$INSTANCE.conf"

function get_conf_value()
{
    local filepath=$1
    local name=$2

    grep -e "^$name\s*=.*" $filepath | head -n 1 | sed -re "s/^$name\s*=\s*(.*)/\1/g"
}

host=$(get_conf_value "$instance_conf_file" host)
port=$(get_conf_value "$instance_conf_file" port)
db=$(get_conf_value "$instance_conf_file" name)

psql -h $host -p $port $db minerva_admin -c '
BEGIN;
TRUNCATE TABLE directory.entity_link_denorm;
INSERT INTO directory.entity_link_denorm
SELECT
	entity.id,
	array_agg(lower(tag.name)),
	lower(entity.name)
FROM directory.entity
JOIN directory.entitytaglink etl ON etl.entity_id = entity.id
JOIN directory.tag ON tag.id = etl.tag_id
GROUP BY entity.id;
COMMIT;
CLUSTER directory.entity_link_denorm USING entity_link_denorm_name_idx;
ANALYZE directory.entity_link_denorm;
'
