FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    ca-certificates \
    software-properties-common \
    python3 \
    python3-pip

RUN pip3 install \
    docker \
    pytest

RUN printf 'deb [trusted=yes] https://packages.hendrikx-itc.nl/hitc/common/bionic/unstable/dists/bionic/ bionic unstable' > /etc/apt/sources.list
RUN apt-get update