FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    software-properties-common \
    python3 \
    python3-pip

RUN pip3 install \
    docker \
    pytest
 
RUN apt-add-repository -y 'deb https://packages.hendrikx-itc.nl/hitc/common/bionic/unstable/ bionic main'
RUN chown -R 996:996 /etc/apt/sources.list