FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip

RUN pip3 install \
    docker \
    pytest
 
RUN add-apt-repository "deb [trusted=yes] https://packages.hendrikx-itc.nl/hitc/common/bionic/unstable/ unstable main"
