FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        dpkg-dev \
        debhelper \
        devscripts \
        equivs \
        python3-psycopg2

COPY build-package /usr/bin/

RUN mkdir /package && chmod 777 /package

VOLUME ["/package/source", "/package/build"]

WORKDIR /package/source

CMD ["build-package"]
