FROM python:latest

RUN apt update && apt install -y \
    git \
    postgresql-contrib \
    postgresql-client \
    gcc \
    python3-dev 

RUN pip3 install \
    psycopg2 \
    pytest\
    pytest-custom_exit_code \
    pytz \
    docker

COPY . /minerva-etl
RUN pip3 install /minerva-etl
