FROM ubuntu:18.04

RUN sed -i 's/security\.ubuntu\.com/archive.ubuntu.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
        dpkg-dev \
        debhelper \
        devscripts \
        equivs

COPY build-package /usr/bin/

RUN mkdir /package && chmod 777 /package

VOLUME ["/package/source", "/package/build"]

WORKDIR /package/source

CMD ["build-package"]
