#!/bin/bash
set -e
set -o pipefail

function invoke_psql()
{
	psql --no-psqlrc --set ON_ERROR_STOP=1 "$@"
}


function runsql()
{
	local command="$@"

	invoke_psql --command "$command"
}

runsql 'CREATE EXTENSION postgis'

runsql 'GRANT SELECT ON public.geometry_columns TO PUBLIC'
runsql 'GRANT SELECT ON public.spatial_ref_sys TO PUBLIC'
