#!/bin/bash
set -e

psql -d postgres -c "CREATE DATABASE minerva;"

psql -d minerva -c 'CREATE EXTENSION pgtap;'

/vagrant/provision/salt/roots/salt/resources/install-db-deps

PGDATABASE=minerva /vagrant/schema/run-scripts /vagrant/schema/scripts
