#!/usr/bin/env python3
import sys
import argparse

from minerva.commands import datasource, trendstore, entitytype, loaddata


def main():
    parser = argparse.ArgumentParser(
        description='Minerva administration tool set'
    )

    subparsers = parser.add_subparsers()

    datasource.setup_command_parser(subparsers)
    trendstore.setup_command_parser(subparsers)
    entitytype.setup_command_parser(subparsers)
    loaddata.setup_command_parser(subparsers)

    args = parser.parse_args()

    if 'cmd' not in args:
        parser.print_help()

        return 0
    else:
        return args.cmd(args)


if __name__ == '__main__':
    sys.exit(main())
