SELECT dimension.update_month();
SELECT dimension.update_week();
SELECT dimension.update_day();
SELECT dimension.update_hour();
SELECT dimension.update_quarter();
SELECT dimension.update_four_consec_qtr();
SELECT dimension.update_month_15m();
SELECT dimension.update_week_15m();
SELECT dimension.update_day_15m();
